FROM node:10

RUN git clone https://github.com/kevingonzalez7997/e-commerce-application-on-AWS-using-ECS.git

WORKDIR e-commerce-application-on-AWS-using-ECS/frontend/

RUN npm install --save-dev @babel/plugin-proposal-private-property-in-object

RUN npm install

EXPOSE 3000

CMD ["npm", "start"]