FROM python:3.9

RUN git clone https://github.com/kevingonzalez7997/e-commerce-application-on-AWS-using-ECS.git

WORKDIR e-commerce-application-on-AWS-using-ECS/backend/

RUN pip install -r requirements.txt

EXPOSE 8000

RUN python manage.py migrate

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]