FROM python:3.9

RUN git clone https://github.com/kevingonzalez7997/e_com_app_on_AWS_using_ECS.git

WORKDIR e_com_app_on_AWS_using_ECS/backend/

RUN pip install -r requirements.txt

EXPOSE 8000

RUN python manage.py migrate

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]